name: SyncerD Azure DevOps to AWS CodeCommit

on:
  push:
    branches:
      - feature/syncerd-github-to-azure-test

  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::924144197303:role/SyncerD-GitHubActions
          aws-region: us-east-1

      - name: Verify AWS identity
        run: |
          aws sts get-caller-identity

      - name: SyncerD Azure DevOps to AWS CodeCommit
        uses: clouddrove/syncerd@v0.2.2
        env:
          SYNCERD_GIT_SOURCE_TOKEN: ${{ secrets.SYNCERD_GIT_ADO_TOKEN }}

          SYNCERD_GIT_CODECOMMIT_SOURCE_GIT_USERNAME: ${{ secrets.SYNCERD_GIT_CODECOMMIT_SOURCE_GIT_USERNAME }}
          SYNCERD_GIT_CODECOMMIT_SOURCE_GIT_PASSWORD: ${{ secrets.SYNCERD_GIT_CODECOMMIT_SOURCE_GIT_PASSWORD }}

        with:
          command: git-sync
          config: syncerd.yaml
          once: "true"
          dry-run: "true"
          report: syncerd-report/azure-to-codecommit.json
          log-format: text

      - name: Show SyncerD report
        if: always()
        run: |
          sudo ls -la syncerd-report || true
          sudo cat syncerd-report/azure-to-codecommit.json || true