name: SyncerD GitLab to Azure DevOps

on:
  push:
    branches:
      - feature/syncerd-github-to-azure-test

permissions:
  contents: read

jobs:
  git-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: SyncerD GitLab to Azure DevOps
        uses: clouddrove/syncerd@v0.2.2
        env:
          # GitLab token
          SYNCERD_GIT_SOURCE_TOKEN: ${{ secrets.SYNCERD_GIT_GITLAB_TOKEN }}

          # Azure DevOps PAT
          SYNCERD_GIT_DESTINATION_TOKEN: ${{ secrets.SYNCERD_GIT_ADO_TOKEN }}

        with:
          command: git-sync
          config: syncerd.yaml
          once: "true"
          dry-run: "false"
          report: syncerd-report/gitlab-to-azure.json
          log-format: text

      - name: Show SyncerD report
        if: always()
        run: |
          sudo ls -la syncerd-report || true
          sudo cat syncerd-report/gitlab-to-azure.json || true